-- CREATE ROLE 
CREATE ROLE reader WITH LOGIN PASSWORD 'Pxt2pUdzruKWA6DRgmHNpEpE2G3Aycjt';
-- GRANT ACCESS TO DATABASE
GRANT CONNECT ON DATABASE "STIV" TO reader;

-- GRANT ACCESS TO pterodactyl SCHEMA
GRANT USAGE ON SCHEMA pterodactyl TO reader;
GRANT SELECT ON ALL TABLES IN SCHEMA pterodactyl TO reader;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA pterodactyl TO reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA pterodactyl
GRANT SELECT ON TABLES TO reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA pterodactyl
GRANT SELECT ON SEQUENCES TO reader;

REVOKE CREATE ON SCHEMA pterodactyl FROM reader;

-- REVOKE ACCESS TO SENSITIVE TABLES
REVOKE SELECT ON TABLE pterodactyl.clients FROM reader;
REVOKE SELECT ON TABLE pterodactyl.locations FROM reader;

-- GRANT ACCESS TO shlink SCHEMA
GRANT USAGE ON SCHEMA shlink TO reader;
GRANT SELECT ON ALL TABLES IN SCHEMA shlink TO reader;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA shlink TO reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA shlink
GRANT SELECT ON TABLES TO reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA shlink
GRANT SELECT ON SEQUENCES TO reader;

REVOKE CREATE ON SCHEMA shlink FROM reader;